### ISSUE TITLE
GCE API Coverage tracker

### ISSUE THREAD

**Issue by Temikus** [mitchellh/vagrant-google#81]
The following flags and descriptions are taken from `gcloud compute instances create --help`

- [x] --address ADDRESS
Assigns the given external address to the instance that is created. The address may be an IP address or the name or URI of an address resource. This option can only be used when creating a single instance.

- [ ] --boot-disk-device-name BOOT_DISK_DEVICE_NAME
The name the guest operating system will see for the boot disk as. This option can only be specified if a new boot disk is being created (as opposed to mounting an existing persistent disk).

- [x] --boot-disk-size BOOT_DISK_SIZE
The size of the boot disk. This option can only be specified if a new boot disk is being created (as opposed to mounting an existing persistent disk). 

- [x] --boot-disk-type BOOT_DISK_TYPE
The type of the boot disk. This option can only be specified if a new boot disk is being created (as opposed to mounting an existing persistent disk).

- [x] --can-ip-forward
If provided, allows the instances to send and receive packets with non-matching destination or source IP addresses.

- [ ] --description DESCRIPTION
Specifies a textual description of the instances.

- [ ] --disk PROPERTY=VALUE
Attaches persistent disks to the instances. The disks specified must already exist.

  - [x] name
  The disk to attach to the instances. When creating more than one instance and using this property, the only valid mode for attaching the disk is read-only (see mode below).

  - [ ] mode
  Specifies the mode of the disk. Supported options are ro for read-only and rw for read-write. If omitted, rw is used as a default. It is an error for mode to be rw when creating more than one instance because read-write disks can only be attached to a single instance.

  - [x] boot
  If yes, indicates that this is a boot disk. The virtual machines will use the first partition of the disk for their root file systems. The default value for this is no.

  - [ ] device-name
  An optional name that indicates the disk name the guest operating system will see. If omitted, a device name of the form persistent-disk-N will be used.

  - [x] auto-delete
  If yes, this persistent disk will be automatically deleted when the instance is deleted. However, if the disk is later detached from the instance, this option won’t apply. The default value for this is no.

  - [x] --image IMAGE 
  Specifies the boot image for the instances. For each instance, a new boot disk will be created from the given image. Each boot disk will have the same name as the instance.

  - [x] --image-project IMAGE_PROJECT
  The project against which all image references will be resolved. See --image for more details.

- [ ] --local-ssd PROPERTY=VALUE
Attaches a local SSD to the instances. This flag is currently in BETA and may change without notice.

    - [ ] device-name
      Optional. A name that indicates the disk name the guest operating system will see. If omitted, a device name of the form local-ssd-N will be used.

    - [ ] interface
      Optional. The kind of disk interface exposed to the VM for this SSD. Valid values are SCSI and NVME. SCSI is the default and is supported by more guest operating systems. NVME may provide higher performance.

- [x] --machine-type MACHINE_TYPE; default="n1-standard-1"
Specifies the machine type used for the instances. To get a list of available machine types, run gcloud compute machine-types list.

- [x] --maintenance-policy MAINTENANCE_POLICY
Specifies the behavior of the instances when their host machines undergo maintenance.  TERMINATE indicates that the instances should be terminated.  MIGRATE indicates that the instances should be migrated to a new host. Choosing MIGRATE will temporarily impact the performance of instances during a migration event. If omitted, MIGRATE is assumed.

- [x] --metadata KEY=VALUE
Metadata to be made available to the guest operating system running on the instances. Each metadata entry is a key/value pair separated by an equals sign.

- [ ] startup-script
Specifies a script that will be executed by the instances once they start running.

- [ ] startup-script-url
Same as startup-script except that the script contents are pulled from a publicly-accessible location on the web.

- [x] --metadata-from-file KEY=LOCAL_FILE_PATH
Same as --metadata except that the value for the entry will be read from a local file. This is useful for values that are too large such as startup-script contents.

- [x] --network NETWORK; default="default"
Specifies the network that the instances will be part of. If omitted, the default network is used.

- [x] --no-address
If provided, the instances will not be assigned external IP addresses.

- [x] --no-boot-disk-auto-delete
If provided, boot disks will not be automatically deleted when their instances are deleted.

- [x] --no-restart-on-failure
If provided, the instances will not be restarted if they are terminated by Compute Engine. By default, failed instances will be restarted. This does not affect terminations performed by the user.

- [x] --no-scopes
If provided, the default scopes (https://www.googleapis.com/auth/devstorage.read_only, https://www.googleapis.com/auth/logging.write) are not added to the instances.

- [x] --scopes SCOPE
Specifies service accounts and scopes for the instances.

- [x] --tags TAG
Specifies a list of tags to apply to the instances for identifying the instances to which network firewall rules will apply. See gcloud compute firewall-rules create(1) for more details.

- [x] --zone ZONE
The zone of the instances to create. If not specified, you will be prompted to select a zone.

**Comment by mlazarov** [comment]
Hi Temikus,

what about instance groups? It will be cool to have option to add instance directly to specific instance group. For example for attaching to specific HTTP/Network LB.

```
gcloud preview instance-groups
```

**Comment by Temikus** [comment]
@mlazarov Thanks for the idea!
I don't see instanceGroup API endpoint set up anywhere in fog-google yet, but as soon as there is one, it should be a trivial matter.

**Comment by mlazarov** [comment]
Hi Temikus, sorry for abusing your todo list. Can you give me some feedback on this instanceGroup api in fog-google (not merged yet):
https://github.com/fog/fog-google/pull/62

Is it covering the requirements for `vagrant-google`?

**Comment by Temikus** [comment]
@mlazarov Not a problem at all. I've quickly glanced through your changes and found some issues, see the PR.

Also, looking into instance groups a bit more deeply, I realised that it is a bit more complicated, since as far as I understand from the doc it isn't possible to just add an instance to the group later. The group needs to be created first with a specified template or a new instance spawned in the group, which will require some heavy branching logic. I created an issue to discuss this further: #105

@mlazarov Since you're proposing this feature, can you please add your vision of how it should ideally work with Vagrant to the issue #105? This will allow me to understand the requirements better.

Thanks!

**Comment by Temikus** [comment]
As soon as #105 is implemented vagrant-google should be feature complete, so closing.

**Comment by utdrmac** [comment]
@Temikus How do you use --no-address within Vagrantfile? I'm trying to make CGE instances without an external/public IP.
